# a basic set of settings that are included for all
default: &default
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  <<: *default

# the db settings used for local development
development:
  adapter: sqlite3
  database: db/development.sqlite3
  <<: *default